### ISSUE TITLE
Error: No Hydra search forms were discovered

### ISSUE THREAD

**Issue by smurp** [comunica/Tutorial-Comunica-Web-Service#5]
Any thoughts?

```shell
$ git checkout tutorial-step/7
...
$ node --version
v12.14.0
$ node index.js 
Listening on port 3000!
(node:58197) UnhandledPromiseRejectionWarning: Error: No Hydra search forms were discovered in the metadata of http://fragments.dbpedia.org/2016-04/en. You may be missing an actor that extracts this metadata
    at ActorRdfResolveQuadPatternHypermedia.chooseForm (/Users/smurp/REPOS/Comunica/Tutorial-Comunica-Querying-Data/node_modules/@comunica/actor-rdf-resolve-quad-pattern-hypermedia/lib/ActorRdfResolveQuadPatternHypermedia.js:36:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async MediatedQuadSource.uriConstructor (/Users/smurp/REPOS/Comunica/Tutorial-Comunica-Querying-Data/node_modules/@comunica/actor-rdf-resolve-quad-pattern-hypermedia/lib/ActorRdfResolveQuadPatternHypermedia.js:66:21)
    at async PromiseProxyIterator.sourceGetter (/Users/smurp/REPOS/Comunica/Tutorial-Comunica-Querying-Data/node_modules/@comunica/actor-rdf-resolve-quad-pattern-hypermedia/lib/MediatedQuadSource.js:94:25)
(node:58197) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 322)
(node:58197) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:58197) UnhandledPromiseRejectionWarning: Error: No Hydra search forms were discovered in the metadata of http://fragments.dbpedia.org/2016-04/en. You may be missing an actor that extracts this metadata
    at ActorRdfResolveQuadPatternHypermedia.chooseForm (/Users/smurp/REPOS/Comunica/Tutorial-Comunica-Querying-Data/node_modules/@comunica/actor-rdf-resolve-quad-pattern-hypermedia/lib/ActorRdfResolveQuadPatternHypermedia.js:36:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async MediatedQuadSource.uriConstructor (/Users/smurp/REPOS/Comunica/Tutorial-Comunica-Querying-Data/node_modules/@comunica/actor-rdf-resolve-quad-pattern-hypermedia/lib/ActorRdfResolveQuadPatternHypermedia.js:66:21)
    at async PromiseProxyIterator.sourceGetter (/Users/smurp/REPOS/Comunica/Tutorial-Comunica-Querying-Data/node_modules/@comunica/actor-rdf-resolve-quad-pattern-hypermedia/lib/MediatedQuadSource.js:94:25)
(node:58197) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 323)
```

**Comment by rubensworks** [comment]
Hmm, could you try again with `https://fragments.dbpedia.org/2016-04/en` as datasource? (the HTTPs-variant)

@joachimvh If this solution fixes the problem, could you update the tutorial to use the HTTPS-based datasource?

**Comment by smurp** [comment]
That worked perfectly!  Thank you.

**Comment by joachimvh** [comment]
https source now gets used in that tutorial. Thx for reporting.
